# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
before_install:
- | 
  gem install cocoapods --pre --quiet --no-ri --no-rdoc
  pod setup --silent
  pod repo update --silent
script:
- set -o pipefail && xcodebuild test -workspace Example/PubNubSimpleHistory.xcworkspace -scheme PubNubSimpleHistory-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
